#!/bin/bash
# Generate Chinese character bitmap font for the Farkle game.
# Uses ImageMagick + Sarasa Gothic SC font to render 12x12 pixel glyphs.
# Output: Rust source code with u16 bitmap arrays.

set -e

FONT="/usr/share/fonts/sarasa-gothic/Sarasa-SemiBold.ttc"
SIZE=12
TMPDIR=$(mktemp -d)
OUTFILE="src/ui/cn_font.rs"

# All Chinese characters needed in the game
CHARS="你对分手回合剩余骰已持掷存选取得游戏结束获胜按车开始无效组零再中个方向思考或文来格移空退重需"

echo "// Auto-generated Chinese 12x12 pixel font from Sarasa Gothic SC" > "$OUTFILE"
echo "// Generated by gen_cn_font.sh" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "extern crate alloc;" >> "$OUTFILE"
echo "use alloc::format;" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "use embedded_graphics::{" >> "$OUTFILE"
echo "    geometry::Point," >> "$OUTFILE"
echo "    mono_font::{MonoFont, MonoTextStyle}," >> "$OUTFILE"
echo "    pixelcolor::Rgb888," >> "$OUTFILE"
echo "    prelude::*," >> "$OUTFILE"
echo "    primitives::{PrimitiveStyle, Rectangle, StyledDrawable}," >> "$OUTFILE"
echo "    text::Text," >> "$OUTFILE"
echo "};" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "pub struct CnChar {" >> "$OUTFILE"
echo "    pub codepoint: u16," >> "$OUTFILE"
echo "    pub glyph: [u16; $SIZE]," >> "$OUTFILE"
echo "}" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "pub static CN_FONT: &[CnChar] = &[" >> "$OUTFILE"

CHAR_COUNT=$(echo -n "$CHARS" | wc -m)
IDX=0
while [ $IDX -lt $CHAR_COUNT ]; do
    CH=$(echo "$CHARS" | cut -c $((IDX+1)))
    CP=$(printf "%04X" "'$CH")
    IDX=$((IDX + 1))

    # Render single character to PBM using ImageMagick
    magick -background white -fill black \
        -font "$FONT" \
        -pointsize $((SIZE + 2)) \
        -gravity center \
        -size ${SIZE}x${SIZE} \
        "label:$CH" \
        -resize ${SIZE}x${SIZE}! \
        -threshold 50% \
        "$TMPDIR/c_${CP}.pbm" 2>/dev/null

    # PBM format: P4 header then raw bits
    # Parse the 12x12 bitmap and convert to [u16; 12]
    echo -n "    CnChar { codepoint: 0x$CP, glyph: [" >> "$OUTFILE"

    # Read raw PBM: skip header (P4\nW H\n), then read ceil(W/8)*H bytes
    # For 12x12: ceil(12/8)=2 bytes per row, 12 rows = 24 bytes
    # We need to convert each row's 2 bytes into 12 bits
    python3 -c "
import struct, sys
# Read PBM raw bits
data = open('$TMPDIR/c_${CP}.pbm', 'rb').read()
# Find header end (P4\\nW H\\n)
pos = 0
while data[pos] != 0x20 and data[pos] != 0x0A: pos += 1
pos += 1  # skip space
while data[pos] != 0x0A: pos += 1
pos += 1  # skip newline
bits = data[pos:]
rows = []
bytes_per_row = (12 + 7) // 8  # = 2
for r in range(12):
    row_val = 0
    for b in range(bytes_per_row):
        byte_val = bits[r * bytes_per_row + b]
        for bit in range(8):
            col = b * 8 + bit
            if col < 12 and (byte_val >> (7 - bit)) & 1:
                row_val |= (1 << col)
    rows.append(row_val)
# Format as Rust array
inner = ', '.join(f'0x{v:03X}' for v in rows)
print(inner, end='')
" >> "$OUTFILE"

    echo "] }," >> "$OUTFILE"
done

echo "];" >> "$OUTFILE"
echo "" >> "$OUTFILE"

# Add find_char and draw_mixed_text functions
cat >> "$OUTFILE" << 'RUSTFUNC'

pub fn find_char(ch: char) -> Option<&'static CnChar> {
    let cp = ch as u16;
    CN_FONT.iter().find(|c| c.codepoint == cp)
}

fn draw_cn_char(
    fb: &mut crate::framebuffer::Framebuffer,
    ch: char,
    top_left: Point,
    color: Rgb888,
) -> Point {
    if let Some(cn) = find_char(ch) {
        for (row, &bits) in cn.glyph.iter().enumerate() {
            for col in 0..12 {
                if (bits >> col) & 1 != 0 {
                    let px = top_left.x + col as i32;
                    let py = top_left.y + row as i32;
                    let _ = Rectangle::new(Point::new(px, py), Size::new(1, 1))
                        .draw_styled(&PrimitiveStyle::with_fill(color), fb);
                }
            }
        }
        Point::new(top_left.x + 13, top_left.y)
    } else {
        let _ = Rectangle::new(top_left, Size::new(12, 12))
            .draw_styled(&PrimitiveStyle::with_stroke(Rgb888::new(0xCC, 0x00, 0x00), 1), fb);
        Point::new(top_left.x + 13, top_left.y)
    }
}

pub fn draw_mixed_text(
    fb: &mut crate::framebuffer::Framebuffer,
    text: &str,
    origin: Point,
    color: Rgb888,
    ascii_font: &MonoFont,
) -> Point {
    let mut cursor = origin;
    for ch in text.chars() {
        if ch.is_ascii() {
            if ch != ' ' {
                let s = format!("{}", ch);
                let style = MonoTextStyle::new(ascii_font, color);
                let _ = Text::new(&s, cursor, style).draw(fb);
            }
            cursor.x += (ascii_font.character_size.width + ascii_font.character_spacing) as i32;
        } else {
            cursor = draw_cn_char(fb, ch, cursor, color);
        }
    }
    cursor
}
RUSTFUNC

echo "Generated $CHAR_COUNT characters into $OUTFILE"
rm -rf "$TMPDIR"
